spring:
  redis:
    #    host: 192.168.1.15
    host: 192.168.0.158
    port: 6379
zuul:
  sensitive-headers:
  routes:
    product: /myProduct/**
      sensitiveHeaders:
#  ignored-patterns:
#    - /**/product/list
    # /myProduct/product/list -> /product/product/list
#    aaaaaa:
#      path: /myProduct/**
#      serviceId: product
#management:
#  security:
#    enabled: false
#
