eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&useUnicode=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
#     host: 192.168.1.15
    host: 192.168.0.158
    port: 6379


env:
 dev4

girl:
 name: lili
 age: 24
